from _Common_Functions.base_functions import *
df_all = pd.DataFrame()
df = pd.DataFrame()

data_list = [
    # {'double top fake break out__daily__setup'    : {'scan_clause': ''}},
    # {'double top fake break down__daily__setup'   : {'scan_clause': ''}},

    {'Elliott_4th_Wave_Completed__Yearly__setup'    : {'scan_clause': '( {segments_filter} ( yearly close <= yearly max( 250 , yearly close ) * 0.9 and yearly ema( yearly rsi( 9 ) , 3 ) > yearly wma( yearly rsi( 9 ) , 21 ) and 1 year ago ema( yearly rsi( 9 ) , 3 )<= 1 year ago wma( yearly rsi( 9 ) , 21 ) and yearly close >= yearly max( 250 , yearly close ) * 0.7 and yearly close >= yearly "ew 4 end" and yearly ema( yearly close , 200 ) < yearly close ) ) '}},
    {'Elliott_4th_Wave_Completed__Quarterly__setup' : {'scan_clause': '( {segments_filter} ( quarterly close <= quarterly max( 250 , quarterly close ) * 0.9 and quarterly ema( quarterly rsi( 9 ) , 3 ) > quarterly wma( quarterly rsi( 9 ) , 21 ) and 1 quarter ago ema( quarterly rsi( 9 ) , 3 )<= 1 quarter ago wma( quarterly rsi( 9 ) , 21 ) and quarterly close >= quarterly max( 250 , quarterly close ) * 0.7 and quarterly close >= quarterly "ew 4 end" and quarterly ema( quarterly close , 200 ) < quarterly close ) ) '}},
    {'Elliott_4th_Wave_Completed__monthly__setup'   : {'scan_clause': '( {segments_filter} ( monthly close <= monthly max( 250 , monthly close ) * 0.9 and monthly ema( monthly rsi( 9 ) , 3 ) > monthly wma( monthly rsi( 9 ) , 21 ) and 1 month ago ema( monthly rsi( 9 ) , 3 )<= 1 month ago wma( monthly rsi( 9 ) , 21 ) and monthly close >= monthly max( 250 , monthly close ) * 0.7 and monthly close >= monthly "ew 4 end" and monthly ema( monthly close , 200 ) < monthly close ) ) '}},
    {'Elliott_4th_Wave_Completed__weekly__setup'    : {'scan_clause': '( {segments_filter} ( weekly close <= weekly max( 250 , weekly close ) * 0.9 and weekly ema( weekly rsi( 9 ) , 3 ) > weekly wma( weekly rsi( 9 ) , 21 ) and 1 week ago ema( weekly rsi( 9 ) , 3 )<= 1 week ago wma( weekly rsi( 9 ) , 21 ) and weekly close >= weekly max( 250 , weekly close ) * 0.7 and weekly close >= weekly "ew 4 end" and weekly ema( weekly close , 200 ) < weekly close ) ) '}},
    {'Elliott_4th_Wave_Completed__Daily__setup'     : {'scan_clause': '( {segments_filter} ( latest close <= latest max( 250 , latest close ) * 0.9 and latest ema( latest rsi( 9 ) , 3 ) > latest wma( latest rsi( 9 ) , 21 ) and 1 day ago ema( latest rsi( 9 ) , 3 )<= 1 day ago wma( latest rsi( 9 ) , 21 ) and latest close >= latest max( 250 , latest close ) * 0.7 and latest close >= latest "ew 4 end" and latest ema( latest close , 200 ) < latest close ) ) '}},

    {'Double_Top_with_RSI__yearly__setup'           : {'scan_clause': '( {segments_filter} ( ( {cash} ( ( {cash} ( yearly high < 1.02 * 8 years ago high and yearly close < 8 years ago low ) ) or( {cash} ( yearly high < 1.02 * 9 years ago high and yearly close < 9 years ago low ) ) or( {cash} ( yearly high < 1.02 * 10 years ago high and yearly close < 10 years ago low ) ) ) ) and yearly volume > yearly sma( yearly volume , 20 ) * 5 and yearly high > 2 years ago high and yearly high > 3 years ago high and yearly high > 4 years ago high and yearly high > 5 years ago high and yearly high > 6 years ago high and yearly high > 7 years ago high and yearly high > 8 years ago high and yearly high > 9 years ago high and yearly rsi( 14 ) <= 40 ) )'}},
    {'Double_Top_with_RSI__quarterly__setup'        : {'scan_clause': '( {segments_filter} ( ( {cash} ( ( {cash} ( quarterly high < 1.02 * 8 quarters ago high and quarterly close < 8 quarters ago low ) ) or( {cash} ( quarterly high < 1.02 * 9 quarters ago high and quarterly close < 9 quarters ago low ) ) or( {cash} ( quarterly high < 1.02 * 10 quarters ago high and quarterly close < 10 quarters ago low ) ) ) ) and quarterly volume > quarterly sma( quarterly volume , 20 ) * 5 and quarterly high > 2 quarters ago high and quarterly high > 3 quarters ago high and quarterly high > 4 quarters ago high and quarterly high > 5 quarters ago high and quarterly high > 6 quarters ago high and quarterly high > 7 quarters ago high and quarterly high > 8 quarters ago high and quarterly high > 9 quarters ago high and quarterly rsi( 14 ) <= 40 ) )'}},
    {'Double_Top_with_RSI__monthly__setup'          : {'scan_clause': '( {segments_filter} ( ( {cash} ( ( {cash} ( monthly high < 1.02 * 8 months ago high and monthly close < 8 months ago low ) ) or( {cash} ( monthly high < 1.02 * 9 months ago high and monthly close < 9 months ago low ) ) or( {cash} ( monthly high < 1.02 * 10 months ago high and monthly close < 10 months ago low ) ) ) ) and monthly volume > monthly sma( monthly volume , 20 ) * 5 and monthly high > 2 months ago high and monthly high > 3 months ago high and monthly high > 4 months ago high and monthly high > 5 months ago high and monthly high > 6 months ago high and monthly high > 7 months ago high and monthly high > 8 months ago high and monthly high > 9 months ago high and monthly rsi( 14 ) <= 40 ) )'}},
    {'Double_Top_with_RSI__weekly__setup'           : {'scan_clause': '( {segments_filter} ( ( {cash} ( ( {cash} ( weekly high < 1.02 * 8 weeks ago high and weekly close < 8 weeks ago low ) ) or( {cash} ( weekly high < 1.02 * 9 weeks ago high and weekly close < 9 weeks ago low ) ) or( {cash} ( weekly high < 1.02 * 10 weeks ago high and weekly close < 10 weeks ago low ) ) ) ) and weekly volume > weekly sma( weekly volume , 20 ) * 5 and weekly high > 2 weeks ago high and weekly high > 3 weeks ago high and weekly high > 4 weeks ago high and weekly high > 5 weeks ago high and weekly high > 6 weeks ago high and weekly high > 7 weeks ago high and weekly high > 8 weeks ago high and weekly high > 9 weeks ago high and weekly rsi( 14 ) <= 40 ) )'}},
    {'Double_Top_with_RSI__Daily__setup'            : {'scan_clause': '( {segments_filter} ( ( {cash} ( ( {cash} ( latest high < 1.02 * 8 days ago high and latest close < 8 days ago low ) ) or( {cash} ( latest high < 1.02 * 9 days ago high and latest close < 9 days ago low ) ) or( {cash} ( latest high < 1.02 * 10 days ago high and latest close < 10 days ago low ) ) ) ) and latest volume > latest sma( latest volume , 20 ) * 5 and latest high > 2 days ago high and latest high > 3 days ago high and latest high > 4 days ago high and latest high > 5 days ago high and latest high > 6 days ago high and latest high > 7 days ago high and latest high > 8 days ago high and latest high > 9 days ago high and latest rsi( 14 ) <= 40 ) )'}},

    {'Elliott_4th_Wave_Completed__4_hourly__setup'  : {'scan_clause': '( {segments_filter} ( [0] 4 hour close <= [0] 4 hour max( 250 , [0] 4 hour close ) * 0.9 and [0] 4 hour ema( [0] 4 hour rsi( 9 ) , 3 ) > [0] 4 hour wma( [0] 4 hour rsi( 9 ) , 21 ) and [-1] 4 hour ema( [0] 4 hour rsi( 9 ) , 3 )<= [-1] 4 hour wma( [0] 4 hour rsi( 9 ) , 21 ) and [0] 4 hour close >= [0] 4 hour max( 250 , [0] 4 hour close ) * 0.7 and [0] 4 hour close >= [0] 4 hour "ew 4 end" and [0] 4 hour ema( [0] 4 hour close , 200 ) < [0] 4 hour close ) ) '}},
    {'Elliott_4th_Wave_Completed__1_hourly__setup'  : {'scan_clause': '( {segments_filter} ( [0] 1 hour close <= [0] 1 hour max( 250 , [0] 1 hour close ) * 0.9 and [0] 1 hour ema( [0] 1 hour rsi( 9 ) , 3 ) > [0] 1 hour wma( [0] 1 hour rsi( 9 ) , 21 ) and [-1] 1 hour ema( [0] 1 hour rsi( 9 ) , 3 )<= [-1] 1 hour wma( [0] 1 hour rsi( 9 ) , 21 ) and [0] 1 hour close >= [0] 1 hour max( 250 , [0] 1 hour close ) * 0.7 and [0] 1 hour close >= [0] 1 hour "ew 4 end" and [0] 1 hour ema( [0] 1 hour close , 200 ) < [0] 1 hour close ) ) '}},
    {'Elliott_4th_Wave_Completed__15_Minutes__setup': {'scan_clause': '( {segments_filter} ( [0] 15 minute close <= [0] 15 minute max( 250 , [0] 15 minute close ) * 0.9 and [0] 15 minute ema( [0] 15 minute rsi( 9 ) , 3 ) > [0] 15 minute wma( [0] 15 minute rsi( 9 ) , 21 ) and [-1] 15 minute ema( [0] 15 minute rsi( 9 ) , 3 )<= [-1] 15 minute wma( [0] 15 minute rsi( 9 ) , 21 ) and [0] 15 minute close >= [0] 15 minute max( 250 , [0] 15 minute close ) * 0.7 and [0] 15 minute close >= [0] 15 minute "ew 4 end" and [0] 15 minute ema( [0] 15 minute close , 200 ) < [0] 15 minute close ) ) '}},

    {'Double_Top_with_RSI__4_hour__setup'           : {'scan_clause': '( {segments_filter} ( ( {cash} ( ( {cash} ( [0] 4 hour high < 1.02 * [-8] 4 hour high and [0] 4 hour close < [-8] 4 hour low ) ) or( {cash} ( [0] 4 hour high < 1.02 * [-9] 4 hour high and [0] 4 hour close < [-9] 4 hour low ) ) or( {cash} ( [0] 4 hour high < 1.02 * [-10] 4 hour high and [0] 4 hour close < [-10] 4 hour low ) ) ) ) and [0] 4 hour volume > [0] 4 hour sma( [0] 4 hour volume , 20 ) * 5 and [0] 4 hour high > [-2] 4 hour high and [0] 4 hour high > [-3] 4 hour high and [0] 4 hour high > [-4] 4 hour high and [0] 4 hour high > [-5] 4 hour high and [0] 4 hour high > [-6] 4 hour high and [0] 4 hour high > [-7] 4 hour high and [0] 4 hour high > [-8] 4 hour high and [0] 4 hour high > [-9] 4 hour high and [0] 4 hour rsi( 14 ) <= 40 ) )'}},
    {'Double_Top_with_RSI__1_hour__setup'           : {'scan_clause': '( {segments_filter} ( ( {cash} ( ( {cash} ( [0] 1 hour high < 1.02 * [-8] 1 hour high and [0] 1 hour close < [-8] 1 hour low ) ) or( {cash} ( [0] 1 hour high < 1.02 * [-9] 1 hour high and [0] 1 hour close < [-9] 1 hour low ) ) or( {cash} ( [0] 1 hour high < 1.02 * [-10] 1 hour high and [0] 1 hour close < [-10] 1 hour low ) ) ) ) and [0] 1 hour volume > [0] 1 hour sma( [0] 1 hour volume , 20 ) * 5 and [0] 1 hour high > [-2] 1 hour high and [0] 1 hour high > [-3] 1 hour high and [0] 1 hour high > [-4] 1 hour high and [0] 1 hour high > [-5] 1 hour high and [0] 1 hour high > [-6] 1 hour high and [0] 1 hour high > [-7] 1 hour high and [0] 1 hour high > [-8] 1 hour high and [0] 1 hour high > [-9] 1 hour high and [0] 1 hour rsi( 14 ) <= 40 ) )'}},
    {'Double_Top_with_RSI__15_minutes__setup'       : {'scan_clause': '( {segments_filter} ( ( {cash} ( ( {cash} ( [0] 15 minute high < 1.02 * [-8] 15 minute high and [0] 15 minute close < [-8] 15 minute low ) ) or( {cash} ( [0] 15 minute high < 1.02 * [-9] 15 minute high and [0] 15 minute close < [-9] 15 minute low ) ) or( {cash} ( [0] 15 minute high < 1.02 * [-10] 15 minute high and [0] 15 minute close < [-10] 15 minute low ) ) ) ) and [0] 15 minute volume > [0] 15 minute sma( [0] 15 minute volume , 20 ) * 5 and [0] 15 minute high > [-2] 15 minute high and [0] 15 minute high > [-3] 15 minute high and [0] 15 minute high > [-4] 15 minute high and [0] 15 minute high > [-5] 15 minute high and [0] 15 minute high > [-6] 15 minute high and [0] 15 minute high > [-7] 15 minute high and [0] 15 minute high > [-8] 15 minute high and [0] 15 minute high > [-9] 15 minute high and [0] 15 minute rsi( 14 ) <= 40 ) )'}},
]


for data_each_list in data_list:
    data_each_list = {key: {k: val.replace('segments_filter', 'cash')} for key, value in data_each_list.items() for k, val in value.items()}
    key, data = next(iter(data_each_list.items()))
    df = download_chart_ink_technical_analysis_scanner(key, data, 'Cash')
    df_all = pd.concat([df_all, df], ignore_index=True)

print(f"\n🔄 downloading data from the website is complete.")
batch_no = datetime.now().strftime('%Y%m%d%H%M%S')
df_all['Batch_No'] = batch_no  # Add batch number to the DataFrame
chart_ink_to_csv(df_all, 'chart_ink_sample')
print(f"✅ Data saved to chart_in_sample.csv")
